### ISSUE TITLE
Vulnerability learning

### ISSUE THREAD

**Issue by Akuharusmenemanimu** [wr3nchsr/ctf-challenges#1]
Hello, may I discuss some questions with you, if it's convenient?

**Comment by wr3nchsr** [comment]
you can reach out on twitter or using other platforms shown on my [blog](https://wr3nchsr.github.io/)

**Comment by Akuharusmenemanimu** [comment]
> 您可以在 Twitter 上或使用我[博客](https://wr3nchsr.github.io/)上显示的其他平台进行联系

I have sent an email to your mailbox and look forward to your reply。

**Comment by Akuharusmenemanimu** [comment]
> > 您可以在 Twitter 上或使用我[博客](https://wr3nchsr.github.io/)上显示的其他平台进行联系
> 
> I have sent an email to your mailbox and look forward to your reply。

The email that has been sent is in your email with the suffix @ gmail.com. Thank you
